name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    strategy:
      matrix:
        arch: [x64, ia32]

    env:
        npm_config_arch: ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $ENV:GITHUB_OUTPUT

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ matrix.arch }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.arch }}-yarn-

    - run: yarn install --frozen-lockfile

    - run: yarn lint

    - run: yarn type-check

    - run: yarn download:dep

    - run: yarn test
      env:
        DEBUG: ame:*
        DEBUG_COLORS: "1"

    - run: yarn build --arch=${{ matrix.arch }} --publish=never

    - uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: build/*.exe
