# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test & Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn type-check
    - run: yarn download:dep
    - run: yarn build:native
      env:
        GENERATOR: Visual Studio 16 2019
    - run: yarn test
    - run: yarn build --publish never
      env:
        BUILD_NUMBER: ${{ github.sha }}
    - uses: actions/upload-artifact@v2
      if: ${{ matrix.node-version == '14.x' }}
      with:
        name: build-artifact
        path: build/*.exe
